services:
  frontend:
    network_mode: bridge
    container_name: "velivo-hr"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3017:5173"
    env_file:
      - .env
    restart: always
